/**
 * Parity: every TypeScript port must reproduce what the Python registry
 * actually computed.
 *
 * `parity-fixture.json` is generated by `generate-fixture.py`, which imports
 * the real `app.processing.algorithms.registry` — so these expectations come
 * from the same code path the API uses, not from a hand-written guess.
 *
 * Run with `pnpm -F @ramanhub/processing test` (Node's built-in runner; no
 * test framework dependency).
 *
 * ## On tolerance
 *
 * Agreement is checked as max-abs-difference relative to each case's own
 * dynamic range, not as exact equality. The two implementations differ in
 * summation order, and `lstsq` here is Householder QR where NumPy uses SVD —
 * both correct, neither bit-identical. `TOLERANCE` is set well below one
 * screen pixel of a plotted trace, which is the only accuracy a preview owes
 * anyone. Anything a user commits is computed by the server regardless.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import type { PreviewStep } from "../src/index";
import { analyzePca, previewPipeline, toBuffer } from "../src/index";

interface Fixture {
  input: { wavenumbers: number[]; intensities: number[] };
  cases: {
    name: string;
    steps: PreviewStep[];
    wavenumbers: number[];
    intensities: number[];
  }[];
}

/** Max allowed disagreement, as a fraction of the case's own dynamic range. */
const TOLERANCE = 1e-6;

const fixture = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("./parity-fixture.json", import.meta.url)),
    "utf8",
  ),
) as Fixture;

/** Max |a - b| over the arrays, scaled by the reference's dynamic range. */
function relativeDeviation(
  actual: ArrayLike<number>,
  expected: number[],
): number {
  let lo = Infinity;
  let hi = -Infinity;
  for (const v of expected) {
    lo = Math.min(lo, v);
    hi = Math.max(hi, v);
  }
  const scale = Math.max(hi - lo, 1e-12);

  let worst = 0;
  for (let i = 0; i < expected.length; i++) {
    worst = Math.max(worst, Math.abs(actual[i]! - expected[i]!));
  }
  return worst / scale;
}

for (const testCase of fixture.cases) {
  void test(`matches the Python registry: ${testCase.name}`, () => {
    const source = toBuffer(
      fixture.input.wavenumbers,
      fixture.input.intensities,
    );
    const outcome = previewPipeline(source, testCase.steps);
    if (outcome.status !== "ok") {
      assert.fail(
        `expected a preview, got ${outcome.status}: ${outcome.reason}`,
      );
    }

    // Length first: `crop` and `resample` change it, and a length mismatch
    // would otherwise surface as a confusing deviation number.
    assert.equal(
      outcome.spectrum.intensities.length,
      testCase.intensities.length,
      "intensity array length",
    );
    assert.equal(
      outcome.spectrum.wavenumbers.length,
      testCase.wavenumbers.length,
      "wavenumber array length",
    );

    const axisDeviation = relativeDeviation(
      outcome.spectrum.wavenumbers,
      testCase.wavenumbers,
    );
    assert.ok(
      axisDeviation < TOLERANCE,
      `wavenumber axis deviates by ${axisDeviation.toExponential(2)} (limit ${TOLERANCE})`,
    );

    const deviation = relativeDeviation(
      outcome.spectrum.intensities,
      testCase.intensities,
    );
    assert.ok(
      deviation < TOLERANCE,
      `intensities deviate by ${deviation.toExponential(2)} (limit ${TOLERANCE})`,
    );
  });
}

void test("every registered server algorithm has a local port", () => {
  // The fixture only covers what it was told to cover; this guards the case
  // where a new Python algorithm ships and nobody ports it. It is checked
  // against the catalog at runtime too, but failing here is cheaper.
  const covered = new Set(
    fixture.cases.flatMap((c) => c.steps.map((s) => s.type)),
  );
  assert.equal(
    covered.size,
    13,
    `parity fixture covers ${covered.size} of 13 step types`,
  );
});

void test("an unknown step type is refused rather than skipped", () => {
  const source = toBuffer(fixture.input.wavenumbers, fixture.input.intensities);
  const outcome = previewPipeline(source, [
    { type: "raman.not.real", params: {} },
  ]);
  assert.equal(outcome.status, "unsupported");
});

void test("a version newer on the server than locally blocks the preview", () => {
  const source = toBuffer(fixture.input.wavenumbers, fixture.input.intensities);
  const outcome = previewPipeline(source, [{ type: "raman.snv", params: {} }], {
    "raman.snv": "2.0.0",
  });
  assert.equal(outcome.status, "unsupported");
});

void test("previewing does not mutate the source buffer", () => {
  const source = toBuffer(fixture.input.wavenumbers, fixture.input.intensities);
  const before = Float64Array.from(source.intensities);
  previewPipeline(source, [
    { type: "raman.despike", params: {} },
    { type: "raman.snv", params: {} },
  ]);
  assert.deepEqual(Array.from(source.intensities), Array.from(before));
});

/* --- multivariate: PCA / k-means ----------------------------------------- */

interface PcaFixture {
  analysisInputs: { id: string; wavenumbers: number[]; intensities: number[] }[];
  pcaCases: {
    name: string;
    params: { components: number; grid_points: number; clusters?: number };
    output: {
      grid_wavenumbers: number[];
      scores: number[][];
      components: number[][];
      explained_variance_ratio: number[];
      cluster_labels?: number[];
    };
  }[];
}

const pcaFixture = fixture as unknown as PcaFixture;

const analysisInputs = pcaFixture.analysisInputs.map((s) => ({
  id: s.id,
  label: s.id,
  wavenumbers: Float64Array.from(s.wavenumbers),
  intensities: Float64Array.from(s.intensities),
}));

/**
 * Loading vectors and score columns are only defined up to a shared sign — the
 * port fixes signs deterministically, NumPy's SVD does not, so a component may
 * legitimately come back mirrored. Compare on the axis where that is resolved.
 */
function signedDeviation(actual: number[], expected: number[]): number {
  let scale = 0;
  for (const v of expected) scale = Math.max(scale, Math.abs(v));
  scale = Math.max(scale, 1e-12);

  const worst = (flip: number) => {
    let w = 0;
    for (let i = 0; i < expected.length; i++) {
      w = Math.max(w, Math.abs(flip * actual[i]! - expected[i]!));
    }
    return w;
  };
  return Math.min(worst(1), worst(-1)) / scale;
}

for (const testCase of pcaFixture.pcaCases) {
  void test(`matches the Python analysis engine: ${testCase.name}`, () => {
    const result = analyzePca(analysisInputs, {
      components: testCase.params.components,
      gridPoints: testCase.params.grid_points,
      clusters: testCase.params.clusters ?? null,
    });

    assert.deepEqual(
      result.grid.map((v) => Math.round(v * 1e6) / 1e6),
      testCase.output.grid_wavenumbers.map((v) => Math.round(v * 1e6) / 1e6),
      "shared grid",
    );

    // Explained variance is sign-independent, so it is the strictest check
    // available and the one that proves the same subspace was found.
    for (let k = 0; k < testCase.output.explained_variance_ratio.length; k++) {
      const got = result.explainedVarianceRatio[k]!;
      const want = testCase.output.explained_variance_ratio[k]!;
      assert.ok(
        Math.abs(got - want) < 1e-9,
        `component ${k} explained variance: got ${got}, want ${want}`,
      );
    }

    for (let k = 0; k < testCase.output.components.length; k++) {
      const dev = signedDeviation(
        result.components[k]!,
        testCase.output.components[k]!,
      );
      assert.ok(dev < 1e-8, `loading ${k} deviates by ${dev.toExponential(2)}`);
    }

    for (let k = 0; k < testCase.output.explained_variance_ratio.length; k++) {
      const gotColumn = result.scores.map((row) => row[k]!);
      const wantColumn = testCase.output.scores.map((row) => row[k]!);
      const dev = signedDeviation(gotColumn, wantColumn);
      assert.ok(dev < 1e-8, `score column ${k} deviates by ${dev.toExponential(2)}`);
    }

    if (testCase.output.cluster_labels) {
      assert.deepEqual(
        result.clusterLabels,
        testCase.output.cluster_labels,
        "cluster labels",
      );
    }
  });
}

void test("PCA refuses spectra that barely overlap", () => {
  const [first] = analysisInputs;
  const shifted = {
    ...first!,
    id: "shifted",
    wavenumbers: Float64Array.from(
      Array.from(first!.wavenumbers, (v) => v + 5000),
    ),
  };
  assert.throws(
    () => analyzePca([first!, shifted], {}),
    /overlap/i,
    "non-overlapping spectra must be refused, not silently truncated",
  );
});

void test("PCA needs at least two spectra", () => {
  assert.throws(() => analyzePca(analysisInputs.slice(0, 1), {}), /two spectra/i);
});
