/**
 * Parity: every TypeScript port must reproduce what the Python registry
 * actually computed.
 *
 * `parity-fixture.json` is generated by `generate-fixture.py`, which imports
 * the real `app.processing.algorithms.registry` — so these expectations come
 * from the same code path the API uses, not from a hand-written guess.
 *
 * Run with `pnpm -F @ramanhub/processing test` (Node's built-in runner; no
 * test framework dependency).
 *
 * ## On tolerance
 *
 * Agreement is checked as max-abs-difference relative to each case's own
 * dynamic range, not as exact equality. The two implementations differ in
 * summation order, and `lstsq` here is Householder QR where NumPy uses SVD —
 * both correct, neither bit-identical. `TOLERANCE` is set well below one
 * screen pixel of a plotted trace, which is the only accuracy a preview owes
 * anyone. Anything a user commits is computed by the server regardless.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import type { PreviewStep } from "../src/index";
import { previewPipeline, toBuffer } from "../src/index";

interface Fixture {
  input: { wavenumbers: number[]; intensities: number[] };
  cases: {
    name: string;
    steps: PreviewStep[];
    wavenumbers: number[];
    intensities: number[];
  }[];
}

/** Max allowed disagreement, as a fraction of the case's own dynamic range. */
const TOLERANCE = 1e-6;

const fixture = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("./parity-fixture.json", import.meta.url)),
    "utf8",
  ),
) as Fixture;

/** Max |a - b| over the arrays, scaled by the reference's dynamic range. */
function relativeDeviation(
  actual: ArrayLike<number>,
  expected: number[],
): number {
  let lo = Infinity;
  let hi = -Infinity;
  for (const v of expected) {
    lo = Math.min(lo, v);
    hi = Math.max(hi, v);
  }
  const scale = Math.max(hi - lo, 1e-12);

  let worst = 0;
  for (let i = 0; i < expected.length; i++) {
    worst = Math.max(worst, Math.abs(actual[i]! - expected[i]!));
  }
  return worst / scale;
}

for (const testCase of fixture.cases) {
  void test(`matches the Python registry: ${testCase.name}`, () => {
    const source = toBuffer(
      fixture.input.wavenumbers,
      fixture.input.intensities,
    );
    const outcome = previewPipeline(source, testCase.steps);
    if (outcome.status !== "ok") {
      assert.fail(
        `expected a preview, got ${outcome.status}: ${outcome.reason}`,
      );
    }

    // Length first: `crop` and `resample` change it, and a length mismatch
    // would otherwise surface as a confusing deviation number.
    assert.equal(
      outcome.spectrum.intensities.length,
      testCase.intensities.length,
      "intensity array length",
    );
    assert.equal(
      outcome.spectrum.wavenumbers.length,
      testCase.wavenumbers.length,
      "wavenumber array length",
    );

    const axisDeviation = relativeDeviation(
      outcome.spectrum.wavenumbers,
      testCase.wavenumbers,
    );
    assert.ok(
      axisDeviation < TOLERANCE,
      `wavenumber axis deviates by ${axisDeviation.toExponential(2)} (limit ${TOLERANCE})`,
    );

    const deviation = relativeDeviation(
      outcome.spectrum.intensities,
      testCase.intensities,
    );
    assert.ok(
      deviation < TOLERANCE,
      `intensities deviate by ${deviation.toExponential(2)} (limit ${TOLERANCE})`,
    );
  });
}

void test("every registered server algorithm has a local port", () => {
  // The fixture only covers what it was told to cover; this guards the case
  // where a new Python algorithm ships and nobody ports it. It is checked
  // against the catalog at runtime too, but failing here is cheaper.
  const covered = new Set(
    fixture.cases.flatMap((c) => c.steps.map((s) => s.type)),
  );
  assert.equal(
    covered.size,
    13,
    `parity fixture covers ${covered.size} of 13 step types`,
  );
});

void test("an unknown step type is refused rather than skipped", () => {
  const source = toBuffer(fixture.input.wavenumbers, fixture.input.intensities);
  const outcome = previewPipeline(source, [
    { type: "raman.not.real", params: {} },
  ]);
  assert.equal(outcome.status, "unsupported");
});

void test("a version newer on the server than locally blocks the preview", () => {
  const source = toBuffer(fixture.input.wavenumbers, fixture.input.intensities);
  const outcome = previewPipeline(source, [{ type: "raman.snv", params: {} }], {
    "raman.snv": "2.0.0",
  });
  assert.equal(outcome.status, "unsupported");
});

void test("previewing does not mutate the source buffer", () => {
  const source = toBuffer(fixture.input.wavenumbers, fixture.input.intensities);
  const before = Float64Array.from(source.intensities);
  previewPipeline(source, [
    { type: "raman.despike", params: {} },
    { type: "raman.snv", params: {} },
  ]);
  assert.deepEqual(Array.from(source.intensities), Array.from(before));
});
