/**
 * Parity between `src/peaks.ts` and `backend/app/processing/peaks.py`.
 *
 * `peaks-fixture.json` is generated by `generate-peaks-fixture.py`, which runs
 * the real server-side detector — so these expectations cannot drift from the
 * server by being hand-written.
 *
 * ## On tolerance
 *
 * Agreement is asserted to within one 4 cm-1 bin, not bit-exactly. The two
 * implementations use different peak-picking primitives (scipy's `find_peaks`
 * against a hand-rolled local-maximum scan) and only need to agree about which
 * bands exist and which is strongest. The client detector is advisory anyway:
 * `POST /v1/library/match` recomputes peaks server-side, so a disagreement
 * costs a slightly different preview, never a different match.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { detectPeaks, PEAK_DETECTOR_VERSION, toBuffer } from "../src/index";

interface Case {
  name: string;
  wavenumbers: number[];
  intensities: number[];
  expected: {
    peaks: { cm1: number; relHeight: number }[];
    primaryPeakCm1: number | null;
  };
}

const fixture = JSON.parse(
  readFileSync(fileURLToPath(new URL("./peaks-fixture.json", import.meta.url)), "utf8"),
) as { version: string; cases: Case[] };

/** One bin either side — the resolution the prefilter actually cares about. */
const TOLERANCE_CM1 = 4;

void test("the fixture was generated by the version this port mirrors", () => {
  assert.equal(fixture.version, PEAK_DETECTOR_VERSION);
});

for (const testCase of fixture.cases) {
  void test(`peaks agree with Python: ${testCase.name}`, () => {
    const profile = detectPeaks(
      toBuffer(testCase.wavenumbers, testCase.intensities),
    );

    if (testCase.expected.primaryPeakCm1 === null) {
      assert.equal(profile.primaryPeakCm1, null, "expected no bands at all");
      assert.equal(profile.peaks.length, 0);
      return;
    }

    assert.notEqual(profile.primaryPeakCm1, null, "expected to find bands");
    assert.ok(
      Math.abs(profile.primaryPeakCm1! - testCase.expected.primaryPeakCm1) <=
        TOLERANCE_CM1,
      `strongest band: got ${profile.primaryPeakCm1}, expected ${testCase.expected.primaryPeakCm1}`,
    );

    // Every band Python considers significant must be found here too. The
    // reverse is not asserted: an extra low-prominence band in the preview is
    // harmless, a missing major one is not.
    const found = profile.peaks.map((p) => p.cm1);
    for (const expected of testCase.expected.peaks) {
      if (expected.relHeight < 0.2) continue;
      assert.ok(
        found.some((c) => Math.abs(c - expected.cm1) <= TOLERANCE_CM1),
        `missing band near ${expected.cm1} in ${testCase.name}; found ${found.join(", ")}`,
      );
    }
  });
}

void test("a flat trace yields no bands rather than dividing by zero", () => {
  const flat = toBuffer(
    Array.from({ length: 200 }, (_, i) => 100 + i),
    new Array(200).fill(0),
  );
  const profile = detectPeaks(flat);
  assert.equal(profile.peaks.length, 0);
  assert.ok(Number.isFinite(profile.peakToBackground));
});

void test("mismatched array lengths are rejected", () => {
  assert.throws(
    () =>
      detectPeaks({
        wavenumbers: new Float64Array([1, 2, 3]) as never,
        intensities: new Float64Array([1, 2]) as never,
      }),
    /same length/,
  );
});
