"""social graph, shares, pins, collections, handle history

Revision ID: 1e817525ab60
Revises: b2c3d4e5f6a7
Create Date: 2026-08-25 10:00:05.187812

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1e817525ab60'
down_revision: str | Sequence[str] | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_owner_id'), 'collections', ['owner_id'], unique=False)
    op.create_index('uq_collection_owner_slug', 'collections', ['owner_id', 'slug'], unique=True)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name='ck_follow_not_self'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_follow_followee', 'follows', ['followee_id'], unique=False)
    op.create_index('ix_follow_follower', 'follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follows_created_at'), 'follows', ['created_at'], unique=False)
    op.create_index('uq_follow_pair', 'follows', ['follower_id', 'followee_id'], unique=True)
    op.create_table('handle_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('handle', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handle_history_handle'), 'handle_history', ['handle'], unique=True)
    op.create_index(op.f('ix_handle_history_user_id'), 'handle_history', ['user_id'], unique=False)
    op.create_table('collection_spectra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('spectrum_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_spectrum_position', 'collection_spectra', ['collection_id', 'position'], unique=False)
    op.create_index('uq_collection_spectrum', 'collection_spectra', ['collection_id', 'spectrum_id'], unique=True)
    op.create_table('pins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spectrum_id', sa.UUID(), nullable=True),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(spectrum_id IS NOT NULL)::int + (finding_id IS NOT NULL)::int = 1', name='ck_pin_one_target'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pin_user_position', 'pins', ['user_id', 'position'], unique=False)
    op.create_index('uq_pin_finding_user', 'pins', ['finding_id', 'user_id'], unique=True, postgresql_where=sa.text('finding_id IS NOT NULL'))
    op.create_index('uq_pin_spectrum_user', 'pins', ['spectrum_id', 'user_id'], unique=True, postgresql_where=sa.text('spectrum_id IS NOT NULL'))
    op.create_table('shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spectrum_id', sa.UUID(), nullable=True),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(spectrum_id IS NOT NULL)::int + (finding_id IS NOT NULL)::int = 1', name='ck_share_one_target'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_created_at'), 'shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_shares_finding_id'), 'shares', ['finding_id'], unique=False)
    op.create_index(op.f('ix_shares_spectrum_id'), 'shares', ['spectrum_id'], unique=False)
    op.create_index('uq_share_finding_user', 'shares', ['finding_id', 'user_id'], unique=True, postgresql_where=sa.text('finding_id IS NOT NULL'))
    op.create_index('uq_share_spectrum_user', 'shares', ['spectrum_id', 'user_id'], unique=True, postgresql_where=sa.text('spectrum_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_share_spectrum_user', table_name='shares', postgresql_where=sa.text('spectrum_id IS NOT NULL'))
    op.drop_index('uq_share_finding_user', table_name='shares', postgresql_where=sa.text('finding_id IS NOT NULL'))
    op.drop_index(op.f('ix_shares_spectrum_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_finding_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_created_at'), table_name='shares')
    op.drop_table('shares')
    op.drop_index('uq_pin_spectrum_user', table_name='pins', postgresql_where=sa.text('spectrum_id IS NOT NULL'))
    op.drop_index('uq_pin_finding_user', table_name='pins', postgresql_where=sa.text('finding_id IS NOT NULL'))
    op.drop_index('ix_pin_user_position', table_name='pins')
    op.drop_table('pins')
    op.drop_index('uq_collection_spectrum', table_name='collection_spectra')
    op.drop_index('ix_collection_spectrum_position', table_name='collection_spectra')
    op.drop_table('collection_spectra')
    op.drop_index(op.f('ix_handle_history_user_id'), table_name='handle_history')
    op.drop_index(op.f('ix_handle_history_handle'), table_name='handle_history')
    op.drop_table('handle_history')
    op.drop_index('uq_follow_pair', table_name='follows')
    op.drop_index(op.f('ix_follows_created_at'), table_name='follows')
    op.drop_index('ix_follow_follower', table_name='follows')
    op.drop_index('ix_follow_followee', table_name='follows')
    op.drop_table('follows')
    op.drop_index('uq_collection_owner_slug', table_name='collections')
    op.drop_index(op.f('ix_collections_owner_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
