"""module 3/4 fields: spectra search columns, votes, comments

Revision ID: b22da08c1678
Revises: 2c8b3fab9ff7
Create Date: 2026-08-18 22:36:02.760292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22da08c1678'
down_revision: Union[str, Sequence[str], None] = '2c8b3fab9ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spectrum_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_spectrum_id'), 'comments', ['spectrum_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spectrum_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spectrum_id'], ['spectra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spectrum_id', 'user_id', name='uq_vote_spectrum_user')
    )
    op.create_index(op.f('ix_votes_spectrum_id'), 'votes', ['spectrum_id'], unique=False)
    op.add_column('spectra', sa.Column('material_type', sa.String(), nullable=True))
    op.add_column('spectra', sa.Column('excitation_wavelength_nm', sa.Numeric(), nullable=True))
    op.add_column('spectra', sa.Column('snr', sa.Numeric(), nullable=True))
    op.create_index(op.f('ix_spectra_excitation_wavelength_nm'), 'spectra', ['excitation_wavelength_nm'], unique=False)
    op.create_index(op.f('ix_spectra_material_type'), 'spectra', ['material_type'], unique=False)
    op.create_index(op.f('ix_spectra_snr'), 'spectra', ['snr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spectra_snr'), table_name='spectra')
    op.drop_index(op.f('ix_spectra_material_type'), table_name='spectra')
    op.drop_index(op.f('ix_spectra_excitation_wavelength_nm'), table_name='spectra')
    op.drop_column('spectra', 'snr')
    op.drop_column('spectra', 'excitation_wavelength_nm')
    op.drop_column('spectra', 'material_type')
    op.drop_index(op.f('ix_votes_spectrum_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_comments_spectrum_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
