// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/spectra-insight-review/DesignReview.tsx": () => import("../components/mockups/spectra-insight-review/DesignReview.tsx")
};
