const directions={
  helix:{name:"Helix",rationale:"Quiet authority for researchers who need to move from raw signal to trusted record with confidence.",tags:["Precision","Layered depth","Warm signal blue"],code:"DIRECTION 01"},
  field:{name:"Field Notes",rationale:"A more editorial, human register for a research community that remembers the person behind the spectrum.",tags:["Editorial","Human context","Oxide + paper"],code:"DIRECTION 02"},
  atlas:{name:"Signal Atlas",rationale:"Instrument-panel clarity for browsing a growing commons, with provenance made scannable at a glance.",tags:["Discovery","Dense signal","Blueprint ink"],code:"DIRECTION 03"}
};
function chart(compact=false){return `<svg class="spectrum-chart" viewBox="0 0 500 ${compact?120:150}" role="img" aria-label="Raman spectrum chart showing a baseline with peaks around 465 and 800 inverse centimetres"><g class="chart-grid"><path d="M32 20H480M32 50H480M32 80H480${compact?"":"M32 110H480"}`+(compact?"":"M32 140H480")+`</path></g><path class="chart-axis" d="M32 10V${compact?100:130}H480"/><path class="chart-trace" d="M32 ${compact?79:104} C55 ${compact?78:104} 70 ${compact?75:101} 88 ${compact?77:103} S120 ${compact?75:100} 140 ${compact?77:103} C154 ${compact?65:88} 166 ${compact?28:42} 177 ${compact?70:92} S204 ${compact?77:102} 226 ${compact?76:100} C247 ${compact?73:97} 263 ${compact?71:94} 274 ${compact?76:100} S301 ${compact?78:103} 324 ${compact?77:102} C339 ${compact?75:99} 350 ${compact?37:55} 361 ${compact?72:95} S392 ${compact?78:103} 420 ${compact?77:101} S455 ${compact?76:100} 480 ${compact?77:102}"/><circle class="chart-dot" cx="177" cy="${compact?70:92}" r="3"/><circle class="chart-dot" cx="361" cy="${compact?72:95}" r="3"/><text class="chart-label" x="32" y="${compact?115:143}">200</text><text class="chart-label" x="162" y="${compact?115:143}">465</text><text class="chart-label" x="345" y="${compact?115:143}">800</text><text class="chart-label" x="450" y="${compact?115:143}">1200 cm⁻¹</text></svg>`}
document.querySelectorAll("SpectrumChart").forEach(el=>{el.outerHTML=chart(el.getAttribute("compact")==="true")});
const select=document.querySelector("#directionSelect"), stage=document.querySelector("#directionStage"), name=document.querySelector("#directionName"), rationale=document.querySelector("#directionRationale"), tags=document.querySelector("#directionTags"), code=document.querySelector(".direction-code"), label=document.querySelector("#viewLabel"), screens=document.querySelector("#screens");
function setDirection(key){const d=directions[key];document.body.classList.remove("field-mode","atlas-mode");if(key!=="helix")document.body.classList.add(`${key}-mode`);name.textContent=d.name;rationale.textContent=d.rationale;code.textContent=d.code;tags.innerHTML=d.tags.map(t=>`<span>${t}</span>`).join("")}
select.addEventListener("change",e=>setDirection(e.target.value));
document.querySelectorAll(".seg").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".seg").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const mode=btn.dataset.viewport;screens.className=`screens ${mode}`;label.textContent=mode==="compare"?"Desktop + mobile treatments":`${mode[0].toUpperCase()+mode.slice(1)} treatment`;if(mode==="mobile")stage.classList.add("mobile-preview");else stage.classList.remove("mobile-preview")}));
document.querySelectorAll(".space-node").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".space-node").forEach(b=>b.classList.remove("active"));btn.classList.add("active");screens.dataset.space=btn.dataset.space;document.querySelector("#mapNote").textContent={ "my-lab":"Private work stays yours. Publication status is a scientific decision — never a popularity signal.","commons":"Commons is a citable scientific database. Provenance and quality are visible before reuse.","feed":"Feed is conversation around published work. Activity never changes search rank, trust, or evidence."}[btn.dataset.space]}));
setDirection("helix");screens.dataset.space="my-lab";